# Import the Dependencies

In [ ]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV

# Load the dataset

In [4]:
df_train = shuffle(pd.read_csv('C:/Users/Devmallya Karar/Downloads/Human Activity Recognition with Smartphones using SVM/train.csv'))
df_train.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
6345           0.294532          -0.002639          -0.124910   
4416           0.279256          -0.019091          -0.107157   
4778           0.270516          -0.018687          -0.106661   
4391           0.277604          -0.012974          -0.103168   
3448           0.265491          -0.024863          -0.144620   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
6345         -0.958266         -0.919886         -0.888666         -0.960221   
4416         -0.993317         -0.985550         -0.984676         -0.993611   
4778         -0.980296         -0.984012         -0.979764         -0.981795   
4391         -0.993639         -0.909506         -0.941662         -0.994829   
3448         -0.997429         -0.985033         -0.979324         -0.997860   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
6345         -0.918187         -0.894879         -0.890625  ...   
4416         -0.986047         -0.983353         -0.938291  ...   
4778         -0.983237         -0.980693         -0.921831  ...   
4391         -0.923537         -0.943017         -0.936620  ...   
3448         -0.985334         -0.976459         -0.943957  ...   

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
6345                        -0.377679                    -0.086785   
4416                        -0.783919                    -0.013609   
4778                        -0.942200                    -0.020649   
4391                         0.434817                     0.069523   
3448                        -0.816004                     0.015019   

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
6345                             -0.368762                         -0.394381   
4416                              0.524977                         -0.155650   
4778                             -0.299014                         -0.251354   
4391                             -0.107543                          0.871253   
3448                             -0.198841                          0.757156   

      angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
6345                             -0.039073              0.713713   
4416                              0.143045             -0.365450   
4778                              0.132041              0.523182   
4391                              0.748921             -0.789942   
3448                             -0.276329             -0.672401   

      angle(Y,gravityMean)  angle(Z,gravityMean)  subject  Activity  
6345              0.390839              0.842815       28    LAYING  
4416             -0.191343             -0.306967       22   SITTING  
4778             -0.191934             -0.822794       23    LAYING  
4391              0.231198             -0.042204       22  STANDING  
3448              0.317459              0.074217       17  STANDING  

[5 rows x 563 columns]

In [5]:
df_test = shuffle(pd.read_csv('C:/Users/Devmallya Karar/Downloads/Human Activity Recognition with Smartphones using SVM/test.csv'))
df_test.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
1696           0.279694          -0.002717          -0.107911   
2779           0.276247          -0.012142          -0.110010   
2190           0.296648          -0.022489          -0.067332   
521            0.357710          -0.035391          -0.103498   
871            0.296720          -0.041996          -0.114393   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
1696         -0.988935         -0.935707         -0.929419         -0.989691   
2779         -0.995456         -0.981576         -0.971507         -0.996346   
2190         -0.424008         -0.195761         -0.239343         -0.463153   
521          -0.938105         -0.911146         -0.952872         -0.939084   
871           0.274215         -0.364836          0.261395          0.174077   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
1696         -0.938183         -0.919637         -0.930062  ...   
2779         -0.980507         -0.967642         -0.939279  ...   
2190         -0.269152         -0.263449         -0.227032  ...   
521          -0.911805         -0.958296         -0.852659  ...   
871          -0.407135          0.244064          0.613006  ...   

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
1696                        -0.706148                     0.077354   
2779                        -0.880821                     0.141465   
2190                        -0.925483                    -0.008094   
521                         -0.189030                     0.298035   
871                          0.012460                    -0.177369   

      angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
1696                             -0.090078                          0.811081   
2779                              0.007248                          0.087822   
2190                              0.703160                          0.934411   
521                              -0.703922                         -0.125585   
871                               0.797682                          0.933456   

      angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
1696                              0.897070             -0.803593   
2779                              0.128716             -0.803470   
2190                              0.749145             -0.564664   
521                               0.197664              0.546867   
871                               0.655934             -0.800405   

      angle(Y,gravityMean)  angle(Z,gravityMean)  subject            Activity  
1696              0.215370             -0.053176       13            STANDING  
2779              0.195761              0.116133       24            STANDING  
2190              0.303389              0.240133       18    WALKING_UPSTAIRS  
521              -0.881243             -0.106545        4              LAYING  
871               0.076244              0.161622        9  WALKING_DOWNSTAIRS  

[5 rows x 563 columns]

# Check the null values

In [6]:
print("Any missing sample in training set:",df_train.isnull().values.any())
print("Any missing sample in test set:",df_test.isnull().values.any())

Any missing sample in training set: False
Any missing sample in test set: False


# Frequency distribution of classes

In [8]:
train_outcome = pd.crosstab(index=df_train["Activity"], columns="count")
train_outcome

col_0               count
Activity                 
LAYING               1407
SITTING              1286
STANDING             1374
WALKING              1226
WALKING_DOWNSTAIRS    986
WALKING_UPSTAIRS     1073

# Train Test Split

In [9]:
X_train = pd.DataFrame(df_train.drop(['Activity','subject'],axis=1))
Y_train_label = df_train.Activity.values.astype(object)
X_test = pd.DataFrame(df_test.drop(['Activity','subject'],axis=1))
Y_test_label = df_test.Activity.values.astype(object)

In [10]:
print("Dimension of Train set",X_train.shape)
print("Dimension of Test set",X_test.shape)

Dimension of Train set (7352, 561)
Dimension of Test set (2947, 561)


# Data Preprocessing

In [11]:
from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()

In [12]:
encoder.fit(Y_train_label)
Y_train = encoder.transform(Y_train_label)

In [13]:
encoder.fit(Y_test_label)
Y_test = encoder.transform(Y_test_label)

In [14]:
num_cols = X_train._get_numeric_data().columns
print("Number of numeric features:",num_cols.size)

Number of numeric features: 561


In [15]:
names_of_predictors = list(X_train.columns.values)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model Building

In [17]:
# Hyperparameter tuning using grid search and cross validation

In [18]:
params_grid = [{'kernel': ['rbf'], 
                'gamma': [1e-3, 1e-4],
                'C': [1, 10, 100, 1000]},
                {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]

In [19]:
svm_model = GridSearchCV(SVC(), params_grid, cv=5)
svm_model.fit(X_train_scaled, Y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'kernel': ['linear']}])

In [20]:
print('Best score for training data:', svm_model.best_score_)

Best score for training data: 0.9877588941762973


In [21]:
print('Best C:',svm_model.best_estimator_.C,"\n") 
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

Best C: 100 

Best Kernel: rbf 

Best Gamma: 0.001 



In [22]:
final_model = svm_model.best_estimator_
Y_pred = final_model.predict(X_test_scaled)
Y_pred_label = list(encoder.inverse_transform(Y_pred))

# Evaluation

In [23]:
print(confusion_matrix(Y_test_label,Y_pred_label))

[[537   0   0   0   0   0]
 [  3 440  47   0   0   1]
 [  0  13 519   0   0   0]
 [  0   0   0 486   4   6]
 [  0   0   0   6 389  25]
 [  0   0   0  15   2 454]]


In [24]:
print(classification_report(Y_test_label,Y_pred_label))

                    precision    recall  f1-score   support

            LAYING       0.99      1.00      1.00       537
           SITTING       0.97      0.90      0.93       491
          STANDING       0.92      0.98      0.95       532
           WALKING       0.96      0.98      0.97       496
WALKING_DOWNSTAIRS       0.98      0.93      0.95       420
  WALKING_UPSTAIRS       0.93      0.96      0.95       471

          accuracy                           0.96      2947
         macro avg       0.96      0.96      0.96      2947
      weighted avg       0.96      0.96      0.96      2947



In [25]:
print("Training set score for SVM: %f" % final_model.score(X_train_scaled , Y_train))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled  , Y_test ))

Training set score for SVM: 1.000000
Testing  set score for SVM: 0.958602
